"""add_xml_upload_id_and_error_message_to_receivables

Revision ID: 242eebdf08c4
Revises: 996b88dd4a35
Create Date: 2026-05-12 22:19:04.830910+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '242eebdf08c4'
down_revision: Union[str, None] = '996b88dd4a35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receivables', sa.Column('xml_upload_id', sa.UUID(), nullable=True))
    op.add_column('receivables', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receivables', 'error_message')
    op.drop_column('receivables', 'xml_upload_id')
    # ### end Alembic commands ###
