"""initial_schema

Revision ID: 03ba4d49e83e
Revises: 
Create Date: 2026-05-12 21:32:22.186306+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '03ba4d49e83e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('exchange_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_currency', sa.String(length=3), nullable=False),
    sa.Column('to_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=15, scale=8), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('collected_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint('from_currency <> to_currency', name='chk_exchange_rates_different_currencies'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('spread', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receivables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assignor_id', sa.UUID(), nullable=False),
    sa.Column('drawee_id', sa.UUID(), nullable=False),
    sa.Column('product_type_id', sa.UUID(), nullable=False),
    sa.Column('invoice_key', sa.String(length=44), nullable=False),
    sa.Column('invoice_number', sa.String(length=9), nullable=False),
    sa.Column('series', sa.String(length=3), nullable=False),
    sa.Column('issued_at', sa.Date(), nullable=False),
    sa.Column('installment_number', sa.String(length=60), nullable=False),
    sa.Column('products_value', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('freight_value', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('other_value', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('face_value', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('xml_storage_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('available', 'in_batch', 'anticipated')", name='chk_receivables_status'),
    sa.CheckConstraint('assignor_id <> drawee_id', name='chk_receivables_assignor_drawee_different'),
    sa.CheckConstraint('face_value > 0', name='chk_receivables_face_value_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_key', 'installment_number', name='uq_receivables_installment')
    )
    op.create_table('system_params',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Numeric(precision=15, scale=8), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assignor_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'queued', 'approved', 'rejected')", name='chk_batches_status'),
    sa.ForeignKeyConstraint(['assignor_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('batch_items',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('receivable_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['receivable_id'], ['receivables.id'], ),
    sa.PrimaryKeyConstraint('batch_id', 'receivable_id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('receivable_id', sa.UUID(), nullable=False),
    sa.Column('face_value', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('present_value', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('term_days', sa.Integer(), nullable=False),
    sa.Column('spread_used', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('base_rate_used', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('instrument_currency', sa.String(length=3), nullable=False),
    sa.Column('settlement_currency', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate_id', sa.UUID(), nullable=True),
    sa.Column('exchange_rate_used', sa.Numeric(precision=15, scale=8), nullable=True),
    sa.Column('liquidated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint('\n            (instrument_currency = settlement_currency)\n            OR\n            (instrument_currency <> settlement_currency\n             AND exchange_rate_id IS NOT NULL\n             AND exchange_rate_used IS NOT NULL)\n            ', name='chk_transactions_exchange_rate_consistency'),
    sa.CheckConstraint('present_value > 0', name='chk_transactions_present_value_positive'),
    sa.CheckConstraint('term_days > 0', name='chk_transactions_term_positive'),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['exchange_rate_id'], ['exchange_rates.id'], ),
    sa.ForeignKeyConstraint(['receivable_id'], ['receivables.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receivable_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('batch_items')
    op.drop_table('batches')
    op.drop_table('users')
    op.drop_table('system_params')
    op.drop_table('receivables')
    op.drop_table('product_types')
    op.drop_table('exchange_rates')
    op.drop_table('companies')
    # ### end Alembic commands ###
