"""add_currencies_table_and_company_social_reason

Revision ID: 79be00a733d1
Revises: d440e2d85f3b
Create Date: 2026-05-13 21:01:22.532499+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '79be00a733d1'
down_revision: Union[str, None] = 'd440e2d85f3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('currencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('is_base', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # Add nullable first, copy data, then enforce not null
    op.add_column('companies', sa.Column('social_reason', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('fantasy_name', sa.String(length=255), nullable=True))
    op.execute("UPDATE companies SET social_reason = name")
    op.alter_column('companies', 'social_reason', nullable=False)
    op.drop_column('companies', 'name')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('companies', 'fantasy_name')
    op.drop_column('companies', 'social_reason')
    op.drop_table('currencies')
    # ### end Alembic commands ###
